Adds routing handler unit tests
cw75/high-performance-lattices pull request #105
Opened 2018-07-20 22:09 UTC by saurav-c

This replaces PR (#104).

2018-07-23 16:57 UTC, vsreekanti requested changes
Seems like 3 of the 5 test files are empty. Is there anything that's blocking writing those tests?

2018-07-23 16:57 UTC, vsreekanti commented on tests/bedrock/route/CMakeLists.txt
> +SET(KVS_SRC_DIR ${CMAKE_SOURCE_DIR}/src/bedrock/route)
Nit: This variable should be `ROUTE_SRC_DIR`.

2018-07-23 16:57 UTC, vsreekanti commented on tests/bedrock/route/routing_handler_base.hpp
> +    kSelfTierId = 1;
Where is `kSelfTierId` being used? The routing tier shouldn't have a tier id.

2018-07-24 20:39 UTC, saurav-c commented
Unit tests have been added for all routing handlers.

2018-07-24 20:48 UTC, vsreekanti approved these changes

2018-07-24 20:49 UTC, vsreekanti commented
Awesome, great job!

2018-07-24 20:49 UTC, merged